### ISSUE TITLE
error in complex operations: bug1

### ISSUE THREAD

**Issue by andreacortis** [andreacortis/SemanticQuantities#6]
======================================================================
ERROR: tests.test_05
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/acortis/my_codes/SemanticQuantities/tests_suite/tests.py", line 79, in test_05
    c = m/v/phi
  File "/Users/acortis/my_codes/SemanticQuantities/.quant/lib/python3.9/site-packages/pint/quantity.py", line 1270, in __truediv__
    return self._mul_div(other, operator.truediv)
  File "/Users/acortis/my_codes/SemanticQuantities/.quant/lib/python3.9/site-packages/pint/quantity.py", line 115, in wrapped
    return f(self, *args, **kwargs)
  File "/Users/acortis/my_codes/SemanticQuantities/.quant/lib/python3.9/site-packages/pint/quantity.py", line 95, in wrapped
    result = f(self, *args, **kwargs)
  File "/Users/acortis/my_codes/SemanticQuantities/.quant/lib/python3.9/site-packages/pint/quantity.py", line 1216, in _mul_div
    magnitude = magnitude_op(self._magnitude, other_magnitude)
TypeError: unsupported operand type(s) for /: 'AffineScalarFunc' and 'Porosity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/acortis/my_codes/SemanticQuantities/tests_suite/tests.py", line 82, in test_05
    raise RuntimeError
RuntimeError

**Comment by andreacortis** [comment]
the issue has to do with partial evaluation of expressions. I need to overload the operations so that they can also operate in mix of pint quantities and semantic quantities. As an example:
```
In [1]: from quantities import quantity_maker, Limits, Q_
   ...: from pint import DimensionalityError
   ...: from uncertainties import ufloat, unumpy
   ...: from typeguard import typechecked
   ...: import numpy as np
   ...:
   ...: Mass = quantity_maker('Mass','kg')
   ...: Volume = quantity_maker('Volume','m^3')
   ...: Density = quantity_maker('Density','kg/m^3')
   ...: Porosity = quantity_maker('Porosity', 'm^3/m^3')

In [2]: m = Mass(name='m', quantity=Q_('6 kg'))

In [3]: v = Volume(name='v', quantity=Q_(ufloat(3, 0.2),'m^3'))

In [4]: phi = Porosity(name='phi',quantity=Q_('0.30 '))

In [5]: type(m/v)
Out[5]: pint.quantity.build_quantity_class.<locals>.Quantity
```

but
```
In [6]: type(m/v/phi)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-c53d5a38678c> in <module>
----> 1 type(m/v/phi)
[...]
TypeError: unsupported operand type(s) for /: 'AffineScalarFunc' and 'Porosity'
```
